
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod
  namespace: prod
spec:
  template:      
    metadata:
      name: prod
    spec:
      project: default
      source:
        repoURL: https://github.com/R0tt3nT0m4t0/gitops-cert-level-2-examples.git
        targetRevision: HEAD
        path: ./environment-promotion/myapp/prod.yml
      destination:
        server: https://kubernetes.default.svc
        namespace: prod
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true 
          selfHeal: true 
